---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: gastronomie
  label: Gastronomie
  create: all
  match: "**/*"
- type: directory
  path: media-rh
  label: Média et RH
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: https://hub.docker.com/layers/node/library/node/lts-stretch/images/sha256-e05c7e37ce469aff3a6af59799499863cc2708e3d62ee7d62318b76a966ac740?context=explore
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
