---
label: Default
hide_body: true
fields:
- name: titre_de_l_article
  type: text
  config:
    required: false
  label: Titre de l'article
- name: image_de_couverture
  type: file
  config:
    maxSize: 64
  label: Image de couverture
- name: texte_de_l_article
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Texte de l'article
